# Generated by ANTLR 4.11.1
# encoding: utf-8
from pyudunits2._grammar._antlr4_runtime import *
import sys

if sys.version_info[1] > 5:
    from typing import TextIO
else:
    from typing.io import TextIO


def serializedATN():
    return [
        4,
        1,
        22,
        106,
        2,
        0,
        7,
        0,
        2,
        1,
        7,
        1,
        2,
        2,
        7,
        2,
        2,
        3,
        7,
        3,
        2,
        4,
        7,
        4,
        2,
        5,
        7,
        5,
        2,
        6,
        7,
        6,
        2,
        7,
        7,
        7,
        2,
        8,
        7,
        8,
        1,
        0,
        3,
        0,
        20,
        8,
        0,
        1,
        0,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        3,
        1,
        27,
        8,
        1,
        1,
        1,
        1,
        1,
        3,
        1,
        31,
        8,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        3,
        1,
        37,
        8,
        1,
        1,
        1,
        1,
        1,
        3,
        1,
        41,
        8,
        1,
        1,
        1,
        1,
        1,
        3,
        1,
        45,
        8,
        1,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        1,
        2,
        4,
        2,
        60,
        8,
        2,
        11,
        2,
        12,
        2,
        61,
        1,
        2,
        5,
        2,
        65,
        8,
        2,
        10,
        2,
        12,
        2,
        68,
        9,
        2,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        3,
        3,
        81,
        8,
        3,
        1,
        4,
        1,
        4,
        1,
        4,
        1,
        4,
        1,
        4,
        3,
        4,
        88,
        8,
        4,
        1,
        5,
        1,
        5,
        1,
        5,
        1,
        5,
        1,
        5,
        1,
        5,
        3,
        5,
        96,
        8,
        5,
        1,
        6,
        1,
        6,
        1,
        7,
        1,
        7,
        3,
        7,
        102,
        8,
        7,
        1,
        8,
        1,
        8,
        1,
        8,
        0,
        1,
        4,
        9,
        0,
        2,
        4,
        6,
        8,
        10,
        12,
        14,
        16,
        0,
        2,
        2,
        0,
        1,
        1,
        9,
        9,
        1,
        0,
        20,
        22,
        115,
        0,
        19,
        1,
        0,
        0,
        0,
        2,
        44,
        1,
        0,
        0,
        0,
        4,
        46,
        1,
        0,
        0,
        0,
        6,
        80,
        1,
        0,
        0,
        0,
        8,
        87,
        1,
        0,
        0,
        0,
        10,
        95,
        1,
        0,
        0,
        0,
        12,
        97,
        1,
        0,
        0,
        0,
        14,
        101,
        1,
        0,
        0,
        0,
        16,
        103,
        1,
        0,
        0,
        0,
        18,
        20,
        3,
        2,
        1,
        0,
        19,
        18,
        1,
        0,
        0,
        0,
        19,
        20,
        1,
        0,
        0,
        0,
        20,
        21,
        1,
        0,
        0,
        0,
        21,
        22,
        5,
        0,
        0,
        1,
        22,
        1,
        1,
        0,
        0,
        0,
        23,
        45,
        3,
        4,
        2,
        0,
        24,
        26,
        3,
        4,
        2,
        0,
        25,
        27,
        5,
        18,
        0,
        0,
        26,
        25,
        1,
        0,
        0,
        0,
        26,
        27,
        1,
        0,
        0,
        0,
        27,
        28,
        1,
        0,
        0,
        0,
        28,
        30,
        5,
        12,
        0,
        0,
        29,
        31,
        5,
        18,
        0,
        0,
        30,
        29,
        1,
        0,
        0,
        0,
        30,
        31,
        1,
        0,
        0,
        0,
        31,
        32,
        1,
        0,
        0,
        0,
        32,
        33,
        3,
        14,
        7,
        0,
        33,
        45,
        1,
        0,
        0,
        0,
        34,
        36,
        3,
        4,
        2,
        0,
        35,
        37,
        5,
        18,
        0,
        0,
        36,
        35,
        1,
        0,
        0,
        0,
        36,
        37,
        1,
        0,
        0,
        0,
        37,
        38,
        1,
        0,
        0,
        0,
        38,
        40,
        5,
        12,
        0,
        0,
        39,
        41,
        5,
        18,
        0,
        0,
        40,
        39,
        1,
        0,
        0,
        0,
        40,
        41,
        1,
        0,
        0,
        0,
        41,
        42,
        1,
        0,
        0,
        0,
        42,
        43,
        3,
        16,
        8,
        0,
        43,
        45,
        1,
        0,
        0,
        0,
        44,
        23,
        1,
        0,
        0,
        0,
        44,
        24,
        1,
        0,
        0,
        0,
        44,
        34,
        1,
        0,
        0,
        0,
        45,
        3,
        1,
        0,
        0,
        0,
        46,
        47,
        6,
        2,
        -1,
        0,
        47,
        48,
        3,
        6,
        3,
        0,
        48,
        66,
        1,
        0,
        0,
        0,
        49,
        50,
        10,
        4,
        0,
        0,
        50,
        65,
        3,
        6,
        3,
        0,
        51,
        52,
        10,
        3,
        0,
        0,
        52,
        53,
        5,
        3,
        0,
        0,
        53,
        65,
        3,
        6,
        3,
        0,
        54,
        55,
        10,
        2,
        0,
        0,
        55,
        56,
        5,
        4,
        0,
        0,
        56,
        65,
        3,
        6,
        3,
        0,
        57,
        59,
        10,
        1,
        0,
        0,
        58,
        60,
        5,
        18,
        0,
        0,
        59,
        58,
        1,
        0,
        0,
        0,
        60,
        61,
        1,
        0,
        0,
        0,
        61,
        59,
        1,
        0,
        0,
        0,
        61,
        62,
        1,
        0,
        0,
        0,
        62,
        63,
        1,
        0,
        0,
        0,
        63,
        65,
        3,
        6,
        3,
        0,
        64,
        49,
        1,
        0,
        0,
        0,
        64,
        51,
        1,
        0,
        0,
        0,
        64,
        54,
        1,
        0,
        0,
        0,
        64,
        57,
        1,
        0,
        0,
        0,
        65,
        68,
        1,
        0,
        0,
        0,
        66,
        64,
        1,
        0,
        0,
        0,
        66,
        67,
        1,
        0,
        0,
        0,
        67,
        5,
        1,
        0,
        0,
        0,
        68,
        66,
        1,
        0,
        0,
        0,
        69,
        70,
        3,
        8,
        4,
        0,
        70,
        71,
        3,
        12,
        6,
        0,
        71,
        81,
        1,
        0,
        0,
        0,
        72,
        81,
        3,
        8,
        4,
        0,
        73,
        74,
        3,
        8,
        4,
        0,
        74,
        75,
        5,
        14,
        0,
        0,
        75,
        76,
        3,
        12,
        6,
        0,
        76,
        81,
        1,
        0,
        0,
        0,
        77,
        78,
        3,
        8,
        4,
        0,
        78,
        79,
        5,
        13,
        0,
        0,
        79,
        81,
        1,
        0,
        0,
        0,
        80,
        69,
        1,
        0,
        0,
        0,
        80,
        72,
        1,
        0,
        0,
        0,
        80,
        73,
        1,
        0,
        0,
        0,
        80,
        77,
        1,
        0,
        0,
        0,
        81,
        7,
        1,
        0,
        0,
        0,
        82,
        88,
        3,
        10,
        5,
        0,
        83,
        84,
        5,
        15,
        0,
        0,
        84,
        85,
        3,
        2,
        1,
        0,
        85,
        86,
        5,
        7,
        0,
        0,
        86,
        88,
        1,
        0,
        0,
        0,
        87,
        82,
        1,
        0,
        0,
        0,
        87,
        83,
        1,
        0,
        0,
        0,
        88,
        9,
        1,
        0,
        0,
        0,
        89,
        96,
        5,
        16,
        0,
        0,
        90,
        91,
        5,
        6,
        0,
        0,
        91,
        92,
        3,
        2,
        1,
        0,
        92,
        93,
        5,
        7,
        0,
        0,
        93,
        96,
        1,
        0,
        0,
        0,
        94,
        96,
        3,
        14,
        7,
        0,
        95,
        89,
        1,
        0,
        0,
        0,
        95,
        90,
        1,
        0,
        0,
        0,
        95,
        94,
        1,
        0,
        0,
        0,
        96,
        11,
        1,
        0,
        0,
        0,
        97,
        98,
        7,
        0,
        0,
        0,
        98,
        13,
        1,
        0,
        0,
        0,
        99,
        102,
        3,
        12,
        6,
        0,
        100,
        102,
        5,
        11,
        0,
        0,
        101,
        99,
        1,
        0,
        0,
        0,
        101,
        100,
        1,
        0,
        0,
        0,
        102,
        15,
        1,
        0,
        0,
        0,
        103,
        104,
        7,
        1,
        0,
        0,
        104,
        17,
        1,
        0,
        0,
        0,
        13,
        19,
        26,
        30,
        36,
        40,
        44,
        61,
        64,
        66,
        80,
        87,
        95,
        101,
    ]


class udunits2Parser(Parser):
    grammarFileName = "udunits2Parser.g4"

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [DFA(ds, i) for i, ds in enumerate(atn.decisionToState)]

    sharedContextCache = PredictionContextCache()

    literalNames = [
        "<INVALID>",
        "<INVALID>",
        "'+'",
        "<INVALID>",
        "<INVALID>",
        "'.'",
        "'('",
        "')'",
        "':'",
    ]

    symbolicNames = [
        "<INVALID>",
        "SIGNED_INT",
        "PLUS",
        "MULTIPLY",
        "DIVIDE",
        "PERIOD",
        "OPEN_PAREN",
        "CLOSE_PAREN",
        "SEMICOLON",
        "INT",
        "E_POWER",
        "FLOAT",
        "SHIFT_OP",
        "UNICODE_EXPONENT",
        "RAISE",
        "LOG",
        "ID",
        "LATIN_SUBSET",
        "WS",
        "ERRORCHARACTER",
        "DATE",
        "TIMESTAMP",
        "DT_T_CLOCK",
    ]

    RULE_unit_spec = 0
    RULE_shift_spec = 1
    RULE_product = 2
    RULE_power = 3
    RULE_logarithm = 4
    RULE_basic_spec = 5
    RULE_integer = 6
    RULE_number = 7
    RULE_timestamp = 8

    ruleNames = [
        "unit_spec",
        "shift_spec",
        "product",
        "power",
        "logarithm",
        "basic_spec",
        "integer",
        "number",
        "timestamp",
    ]

    EOF = Token.EOF
    SIGNED_INT = 1
    PLUS = 2
    MULTIPLY = 3
    DIVIDE = 4
    PERIOD = 5
    OPEN_PAREN = 6
    CLOSE_PAREN = 7
    SEMICOLON = 8
    INT = 9
    E_POWER = 10
    FLOAT = 11
    SHIFT_OP = 12
    UNICODE_EXPONENT = 13
    RAISE = 14
    LOG = 15
    ID = 16
    LATIN_SUBSET = 17
    WS = 18
    ERRORCHARACTER = 19
    DATE = 20
    TIMESTAMP = 21
    DT_T_CLOCK = 22

    def __init__(self, input: TokenStream, output: TextIO = sys.stdout):
        super().__init__(input, output)
        self.checkVersion("4.11.1")
        self._interp = ParserATNSimulator(
            self, self.atn, self.decisionsToDFA, self.sharedContextCache
        )
        self._predicates = None

    class Unit_specContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def EOF(self):
            return self.getToken(udunits2Parser.EOF, 0)

        def shift_spec(self):
            return self.getTypedRuleContext(udunits2Parser.Shift_specContext, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_unit_spec

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitUnit_spec"):
                return visitor.visitUnit_spec(self)
            else:
                return visitor.visitChildren(self)

    def unit_spec(self):
        localctx = udunits2Parser.Unit_specContext(self, self._ctx, self.state)
        self.enterRule(localctx, 0, self.RULE_unit_spec)
        self._la = 0  # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 19
            self._errHandler.sync(self)
            _la = self._input.LA(1)
            if ((_la) & ~0x3F) == 0 and ((1 << _la) & 100930) != 0:
                self.state = 18
                self.shift_spec()

            self.state = 21
            self.match(udunits2Parser.EOF)
        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class Shift_specContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def product(self):
            return self.getTypedRuleContext(udunits2Parser.ProductContext, 0)

        def SHIFT_OP(self):
            return self.getToken(udunits2Parser.SHIFT_OP, 0)

        def number(self):
            return self.getTypedRuleContext(udunits2Parser.NumberContext, 0)

        def WS(self, i: int = None):
            if i is None:
                return self.getTokens(udunits2Parser.WS)
            else:
                return self.getToken(udunits2Parser.WS, i)

        def timestamp(self):
            return self.getTypedRuleContext(udunits2Parser.TimestampContext, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_shift_spec

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitShift_spec"):
                return visitor.visitShift_spec(self)
            else:
                return visitor.visitChildren(self)

    def shift_spec(self):
        localctx = udunits2Parser.Shift_specContext(self, self._ctx, self.state)
        self.enterRule(localctx, 2, self.RULE_shift_spec)
        self._la = 0  # Token type
        try:
            self.state = 44
            self._errHandler.sync(self)
            la_ = self._interp.adaptivePredict(self._input, 5, self._ctx)
            if la_ == 1:
                self.enterOuterAlt(localctx, 1)
                self.state = 23
                self.product(0)
                pass

            elif la_ == 2:
                self.enterOuterAlt(localctx, 2)
                self.state = 24
                self.product(0)
                self.state = 26
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la == 18:
                    self.state = 25
                    self.match(udunits2Parser.WS)

                self.state = 28
                self.match(udunits2Parser.SHIFT_OP)
                self.state = 30
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la == 18:
                    self.state = 29
                    self.match(udunits2Parser.WS)

                self.state = 32
                self.number()
                pass

            elif la_ == 3:
                self.enterOuterAlt(localctx, 3)
                self.state = 34
                self.product(0)
                self.state = 36
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la == 18:
                    self.state = 35
                    self.match(udunits2Parser.WS)

                self.state = 38
                self.match(udunits2Parser.SHIFT_OP)
                self.state = 40
                self._errHandler.sync(self)
                _la = self._input.LA(1)
                if _la == 18:
                    self.state = 39
                    self.match(udunits2Parser.WS)

                self.state = 42
                self.timestamp()
                pass

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class ProductContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def power(self):
            return self.getTypedRuleContext(udunits2Parser.PowerContext, 0)

        def product(self):
            return self.getTypedRuleContext(udunits2Parser.ProductContext, 0)

        def MULTIPLY(self):
            return self.getToken(udunits2Parser.MULTIPLY, 0)

        def DIVIDE(self):
            return self.getToken(udunits2Parser.DIVIDE, 0)

        def WS(self, i: int = None):
            if i is None:
                return self.getTokens(udunits2Parser.WS)
            else:
                return self.getToken(udunits2Parser.WS, i)

        def getRuleIndex(self):
            return udunits2Parser.RULE_product

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitProduct"):
                return visitor.visitProduct(self)
            else:
                return visitor.visitChildren(self)

    def product(self, _p: int = 0):
        _parentctx = self._ctx
        _parentState = self.state
        localctx = udunits2Parser.ProductContext(self, self._ctx, _parentState)
        _prevctx = localctx
        _startState = 4
        self.enterRecursionRule(localctx, 4, self.RULE_product, _p)
        self._la = 0  # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 47
            self.power()
            self._ctx.stop = self._input.LT(-1)
            self.state = 66
            self._errHandler.sync(self)
            _alt = self._interp.adaptivePredict(self._input, 8, self._ctx)
            while _alt != 2 and _alt != ATN.INVALID_ALT_NUMBER:
                if _alt == 1:
                    if self._parseListeners is not None:
                        self.triggerExitRuleEvent()
                    _prevctx = localctx
                    self.state = 64
                    self._errHandler.sync(self)
                    la_ = self._interp.adaptivePredict(self._input, 7, self._ctx)
                    if la_ == 1:
                        localctx = udunits2Parser.ProductContext(
                            self, _parentctx, _parentState
                        )
                        self.pushNewRecursionContext(
                            localctx, _startState, self.RULE_product
                        )
                        self.state = 49
                        if not self.precpred(self._ctx, 4):
                            from pyudunits2._grammar._antlr4_runtime.error.Errors import (
                                FailedPredicateException,
                            )

                            raise FailedPredicateException(
                                self, "self.precpred(self._ctx, 4)"
                            )
                        self.state = 50
                        self.power()
                        pass

                    elif la_ == 2:
                        localctx = udunits2Parser.ProductContext(
                            self, _parentctx, _parentState
                        )
                        self.pushNewRecursionContext(
                            localctx, _startState, self.RULE_product
                        )
                        self.state = 51
                        if not self.precpred(self._ctx, 3):
                            from pyudunits2._grammar._antlr4_runtime.error.Errors import (
                                FailedPredicateException,
                            )

                            raise FailedPredicateException(
                                self, "self.precpred(self._ctx, 3)"
                            )
                        self.state = 52
                        self.match(udunits2Parser.MULTIPLY)
                        self.state = 53
                        self.power()
                        pass

                    elif la_ == 3:
                        localctx = udunits2Parser.ProductContext(
                            self, _parentctx, _parentState
                        )
                        self.pushNewRecursionContext(
                            localctx, _startState, self.RULE_product
                        )
                        self.state = 54
                        if not self.precpred(self._ctx, 2):
                            from pyudunits2._grammar._antlr4_runtime.error.Errors import (
                                FailedPredicateException,
                            )

                            raise FailedPredicateException(
                                self, "self.precpred(self._ctx, 2)"
                            )
                        self.state = 55
                        self.match(udunits2Parser.DIVIDE)
                        self.state = 56
                        self.power()
                        pass

                    elif la_ == 4:
                        localctx = udunits2Parser.ProductContext(
                            self, _parentctx, _parentState
                        )
                        self.pushNewRecursionContext(
                            localctx, _startState, self.RULE_product
                        )
                        self.state = 57
                        if not self.precpred(self._ctx, 1):
                            from pyudunits2._grammar._antlr4_runtime.error.Errors import (
                                FailedPredicateException,
                            )

                            raise FailedPredicateException(
                                self, "self.precpred(self._ctx, 1)"
                            )
                        self.state = 59
                        self._errHandler.sync(self)
                        _la = self._input.LA(1)
                        while True:
                            self.state = 58
                            self.match(udunits2Parser.WS)
                            self.state = 61
                            self._errHandler.sync(self)
                            _la = self._input.LA(1)
                            if not (_la == 18):
                                break

                        self.state = 63
                        self.power()
                        pass

                self.state = 68
                self._errHandler.sync(self)
                _alt = self._interp.adaptivePredict(self._input, 8, self._ctx)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.unrollRecursionContexts(_parentctx)
        return localctx

    class PowerContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def logarithm(self):
            return self.getTypedRuleContext(udunits2Parser.LogarithmContext, 0)

        def integer(self):
            return self.getTypedRuleContext(udunits2Parser.IntegerContext, 0)

        def RAISE(self):
            return self.getToken(udunits2Parser.RAISE, 0)

        def UNICODE_EXPONENT(self):
            return self.getToken(udunits2Parser.UNICODE_EXPONENT, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_power

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitPower"):
                return visitor.visitPower(self)
            else:
                return visitor.visitChildren(self)

    def power(self):
        localctx = udunits2Parser.PowerContext(self, self._ctx, self.state)
        self.enterRule(localctx, 6, self.RULE_power)
        try:
            self.state = 80
            self._errHandler.sync(self)
            la_ = self._interp.adaptivePredict(self._input, 9, self._ctx)
            if la_ == 1:
                self.enterOuterAlt(localctx, 1)
                self.state = 69
                self.logarithm()
                self.state = 70
                self.integer()
                pass

            elif la_ == 2:
                self.enterOuterAlt(localctx, 2)
                self.state = 72
                self.logarithm()
                pass

            elif la_ == 3:
                self.enterOuterAlt(localctx, 3)
                self.state = 73
                self.logarithm()
                self.state = 74
                self.match(udunits2Parser.RAISE)
                self.state = 75
                self.integer()
                pass

            elif la_ == 4:
                self.enterOuterAlt(localctx, 4)
                self.state = 77
                self.logarithm()
                self.state = 78
                self.match(udunits2Parser.UNICODE_EXPONENT)
                pass

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class LogarithmContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def basic_spec(self):
            return self.getTypedRuleContext(udunits2Parser.Basic_specContext, 0)

        def LOG(self):
            return self.getToken(udunits2Parser.LOG, 0)

        def shift_spec(self):
            return self.getTypedRuleContext(udunits2Parser.Shift_specContext, 0)

        def CLOSE_PAREN(self):
            return self.getToken(udunits2Parser.CLOSE_PAREN, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_logarithm

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitLogarithm"):
                return visitor.visitLogarithm(self)
            else:
                return visitor.visitChildren(self)

    def logarithm(self):
        localctx = udunits2Parser.LogarithmContext(self, self._ctx, self.state)
        self.enterRule(localctx, 8, self.RULE_logarithm)
        try:
            self.state = 87
            self._errHandler.sync(self)
            token = self._input.LA(1)
            if token in [1, 6, 9, 11, 16]:
                self.enterOuterAlt(localctx, 1)
                self.state = 82
                self.basic_spec()
                pass
            elif token in [15]:
                self.enterOuterAlt(localctx, 2)
                self.state = 83
                self.match(udunits2Parser.LOG)
                self.state = 84
                self.shift_spec()
                self.state = 85
                self.match(udunits2Parser.CLOSE_PAREN)
                pass
            else:
                raise NoViableAltException(self)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class Basic_specContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def ID(self):
            return self.getToken(udunits2Parser.ID, 0)

        def OPEN_PAREN(self):
            return self.getToken(udunits2Parser.OPEN_PAREN, 0)

        def shift_spec(self):
            return self.getTypedRuleContext(udunits2Parser.Shift_specContext, 0)

        def CLOSE_PAREN(self):
            return self.getToken(udunits2Parser.CLOSE_PAREN, 0)

        def number(self):
            return self.getTypedRuleContext(udunits2Parser.NumberContext, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_basic_spec

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitBasic_spec"):
                return visitor.visitBasic_spec(self)
            else:
                return visitor.visitChildren(self)

    def basic_spec(self):
        localctx = udunits2Parser.Basic_specContext(self, self._ctx, self.state)
        self.enterRule(localctx, 10, self.RULE_basic_spec)
        try:
            self.state = 95
            self._errHandler.sync(self)
            token = self._input.LA(1)
            if token in [16]:
                self.enterOuterAlt(localctx, 1)
                self.state = 89
                self.match(udunits2Parser.ID)
                pass
            elif token in [6]:
                self.enterOuterAlt(localctx, 2)
                self.state = 90
                self.match(udunits2Parser.OPEN_PAREN)
                self.state = 91
                self.shift_spec()
                self.state = 92
                self.match(udunits2Parser.CLOSE_PAREN)
                pass
            elif token in [1, 9, 11]:
                self.enterOuterAlt(localctx, 3)
                self.state = 94
                self.number()
                pass
            else:
                raise NoViableAltException(self)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class IntegerContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def INT(self):
            return self.getToken(udunits2Parser.INT, 0)

        def SIGNED_INT(self):
            return self.getToken(udunits2Parser.SIGNED_INT, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_integer

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitInteger"):
                return visitor.visitInteger(self)
            else:
                return visitor.visitChildren(self)

    def integer(self):
        localctx = udunits2Parser.IntegerContext(self, self._ctx, self.state)
        self.enterRule(localctx, 12, self.RULE_integer)
        self._la = 0  # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 97
            _la = self._input.LA(1)
            if not (_la == 1 or _la == 9):
                self._errHandler.recoverInline(self)
            else:
                self._errHandler.reportMatch(self)
                self.consume()
        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class NumberContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def integer(self):
            return self.getTypedRuleContext(udunits2Parser.IntegerContext, 0)

        def FLOAT(self):
            return self.getToken(udunits2Parser.FLOAT, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_number

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitNumber"):
                return visitor.visitNumber(self)
            else:
                return visitor.visitChildren(self)

    def number(self):
        localctx = udunits2Parser.NumberContext(self, self._ctx, self.state)
        self.enterRule(localctx, 14, self.RULE_number)
        try:
            self.state = 101
            self._errHandler.sync(self)
            token = self._input.LA(1)
            if token in [1, 9]:
                self.enterOuterAlt(localctx, 1)
                self.state = 99
                self.integer()
                pass
            elif token in [11]:
                self.enterOuterAlt(localctx, 2)
                self.state = 100
                self.match(udunits2Parser.FLOAT)
                pass
            else:
                raise NoViableAltException(self)

        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    class TimestampContext(ParserRuleContext):
        __slots__ = "parser"

        def __init__(
            self, parser, parent: ParserRuleContext = None, invokingState: int = -1
        ):
            super().__init__(parent, invokingState)
            self.parser = parser

        def DATE(self):
            return self.getToken(udunits2Parser.DATE, 0)

        def DT_T_CLOCK(self):
            return self.getToken(udunits2Parser.DT_T_CLOCK, 0)

        def TIMESTAMP(self):
            return self.getToken(udunits2Parser.TIMESTAMP, 0)

        def getRuleIndex(self):
            return udunits2Parser.RULE_timestamp

        def accept(self, visitor: ParseTreeVisitor):
            if hasattr(visitor, "visitTimestamp"):
                return visitor.visitTimestamp(self)
            else:
                return visitor.visitChildren(self)

    def timestamp(self):
        localctx = udunits2Parser.TimestampContext(self, self._ctx, self.state)
        self.enterRule(localctx, 16, self.RULE_timestamp)
        self._la = 0  # Token type
        try:
            self.enterOuterAlt(localctx, 1)
            self.state = 103
            _la = self._input.LA(1)
            if not (((_la) & ~0x3F) == 0 and ((1 << _la) & 7340032) != 0):
                self._errHandler.recoverInline(self)
            else:
                self._errHandler.reportMatch(self)
                self.consume()
        except RecognitionException as re:
            localctx.exception = re
            self._errHandler.reportError(self, re)
            self._errHandler.recover(self, re)
        finally:
            self.exitRule()
        return localctx

    def sempred(self, localctx: RuleContext, ruleIndex: int, predIndex: int):
        if self._predicates == None:
            self._predicates = dict()
        self._predicates[2] = self.product_sempred
        pred = self._predicates.get(ruleIndex, None)
        if pred is None:
            raise Exception("No predicate with index:" + str(ruleIndex))
        else:
            return pred(localctx, predIndex)

    def product_sempred(self, localctx: ProductContext, predIndex: int):
        if predIndex == 0:
            return self.precpred(self._ctx, 4)

        if predIndex == 1:
            return self.precpred(self._ctx, 3)

        if predIndex == 2:
            return self.precpred(self._ctx, 2)

        if predIndex == 3:
            return self.precpred(self._ctx, 1)
